title: "Dr. Muhammad Awais Sattar"
description: "Academic Website"
theme: jekyll-theme-cayman

# Navigation menu
nav:
  - name: Home
    link: /
  - name: CV
    link: /cv
  - name: Research
    link: /research
  - name: Publications
    link: /publications
  - name: Teaching
    link: /teaching
  - name: Contact
    link: /contact
